package:
  name: pvapy-boost
  version: 1.78.0

source:
  url: https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - numpy>=1.22

  run:
    - python
    - numpy>=1.22

about:
  home: http://www.boost.org
  license: Boost Software License
  license_file: LICENSE_1_0.txt
  summary: Boost python libraries needed by PvaPy 


