package:
  name: pvapy-boost
  version: 1.72.0

source:
  url: https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - numpy>1.15

  run:
    - python
    - numpy>1.15

about:
  home: http://www.boost.org
  license: Boost Software License
  license_file: LICENSE_1_0.txt
  summary: Boost python libraries needed by PvaPy 


